apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: quasar-fire
type: Opaque
stringData:
  POSTGRES_DB: satellite_tracker
  POSTGRES_USER: tracker
  POSTGRES_PASSWORD: tracker_secret
